#!/bin/sh -e
# Build the source package of this project (.tar.gz file)

dpkg-source \
	--tar-ignore='*.git' \
	--tar-ignore="*.gitignore*" \
	--tar-ignore="*.o" \
	--tar-ignore="*.out" \
	--tar-ignore="*.so" \
	--tar-ignore='*.sw?' \
	--tar-ignore="tests/hex" \
	--tar-ignore='tmp*' \
	-i -b .
