#!/bin/sh -e

#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]
then
    # We want to allow users to add new .ini files in /var/lib/libtld/tlds/...
    #
    mkdir -p /var/lib/libtld/tlds
    if ! test -L /usr/share/libtld/tlds/extensions
    then
        rm -rf /usr/share/libtld/tlds/extensions
        ln -s /var/lib/libtld/tlds /usr/share/libtld/tlds/extensions
    fi
fi

# vim: ts=4 sw=4 et nocindent
