#!/bin/sh -e

#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]
then
    # Create the user directory and link to the README.md so that way the
    # user knows what that folder is about
    #
    mkdir -p /var/lib/libtld/tlds
    if ! test -L /var/lib/libtld/tlds/README.md
    then
        ln -s /usr/share/libtld/tlds/README.md /var/lib/libtld/tlds/README.md
    fi
fi

# vim: ts=4 sw=4 et nocindent
